//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessMatrix.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccessMatrix.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;env:Envelope xmlns:env=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        /// &lt;env:Header&gt;
        ///  &lt;SessionID&gt;{0}&lt;/SessionID&gt;
        /// &lt;/env:Header&gt;
        /// &lt;env:Body&gt;
        ///   &lt;dis:AddObject xmlns:dis=&quot;http://www.sap.com/SBO/DIS&quot; CommandID=&quot;{1}&quot;&gt;
        ///   {2}
        ///   &lt;/dis:AddObject&gt;
        /// &lt;/env:Body&gt;
        ///&lt;/env:Envelope&gt;.
        /// </summary>
        internal static string AddObjectSoapRequest {
            get {
                return ResourceManager.GetString("AddObjectSoapRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testing.
        /// </summary>
        internal static string AppStage {
            get {
                return ResourceManager.GetString("AppStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;BOM&gt;
        ///&lt;BO&gt;
        ///	&lt;AdmInfo&gt;
        ///	&lt;Object&gt;oBusinessPartners&lt;/Object&gt;
        ///	&lt;Version&gt;2&lt;/Version&gt;
        ///	&lt;/AdmInfo&gt;
        ///	&lt;BusinessPartners&gt;
        ///	&lt;row&gt;
        ///	&lt;CardCode&gt;{0}&lt;/CardCode&gt;
        ///	&lt;CardName&gt;{1}&lt;/CardName&gt;
        ///	&lt;/row&gt;
        ///	&lt;/BusinessPartners&gt;
        ///&lt;/BO&gt;
        ///&lt;/BOM&gt;.
        /// </summary>
        internal static string BPSoapRequest {
            get {
                return ResourceManager.GetString("BPSoapRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;env:Envelope xmlns:env=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///  &lt;env:Body&gt;
        ///    &lt;dis:Login xmlns:dis=&quot;http://www.sap.com/SBO/DIS&quot;&gt;
        ///      &lt;DatabaseServer&gt;{0}&lt;/DatabaseServer&gt;
        ///      &lt;DatabaseName&gt;{1}&lt;/DatabaseName&gt;
        ///      &lt;DatabaseType&gt;{2}&lt;/DatabaseType&gt;
        ///      &lt;CompanyUsername&gt;{3}&lt;/CompanyUsername&gt;
        ///	  &lt;CompanyPassword&gt;{4}&lt;/CompanyPassword&gt;
        ///	  &lt;Language&gt;{5}&lt;/Language&gt;
        ///      &lt;LicenseServer&gt;{6}&lt;/LicenseServer&gt;
        ///    &lt;/dis:Login&gt;
        ///  &lt;/env:Body&gt;
        ///&lt;/env:Envelope&gt;.
        /// </summary>
        internal static string DIServerLoginSOAP {
            get {
                return ResourceManager.GetString("DIServerLoginSOAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &quot;AcctCode&quot;, &quot;AcctName&quot; FROM OACT.
        /// </summary>
        internal static string QRY_AllAccounts {
            get {
                return ResourceManager.GetString("QRY_AllAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;BPLName&quot; FROM OBPL T0 WHERE T0.&quot;Disabled&quot; = &apos;N&apos;.
        /// </summary>
        internal static string QRY_AllBranches {
            get {
                return ResourceManager.GetString("QRY_AllBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select &quot;GroupCode&quot;, &quot;GroupName&quot; from OCRG.
        /// </summary>
        internal static string QRY_AllBusinessPartnersGroups {
            get {
                return ResourceManager.GetString("QRY_AllBusinessPartnersGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 WHERE T0.&quot;DimCode&quot; = 1.
        /// </summary>
        internal static string QRY_AllDimension1 {
            get {
                return ResourceManager.GetString("QRY_AllDimension1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 WHERE T0.&quot;DimCode&quot; = 2.
        /// </summary>
        internal static string QRY_AllDimension2 {
            get {
                return ResourceManager.GetString("QRY_AllDimension2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 WHERE T0.&quot;DimCode&quot; = 3.
        /// </summary>
        internal static string QRY_AllDimension3 {
            get {
                return ResourceManager.GetString("QRY_AllDimension3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 WHERE T0.&quot;DimCode&quot; = 4.
        /// </summary>
        internal static string QRY_AllDimension4 {
            get {
                return ResourceManager.GetString("QRY_AllDimension4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 WHERE T0.&quot;DimCode&quot; = 5.
        /// </summary>
        internal static string QRY_AllDimension5 {
            get {
                return ResourceManager.GetString("QRY_AllDimension5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;PrjCode&quot;, T0.&quot;PrjName&quot; FROM OPRJ T0.
        /// </summary>
        internal static string QRY_AllProjects {
            get {
                return ResourceManager.GetString("QRY_AllProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;PrjName&quot;, T0.&quot;PrjCode&quot; FROM OPRJ T0.
        /// </summary>
        internal static string QRY_AllProjectsName {
            get {
                return ResourceManager.GetString("QRY_AllProjectsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;USER_CODE&quot;, T0.&quot;U_NAME&quot; FROM OUSR T0.
        /// </summary>
        internal static string QRY_AllUsers {
            get {
                return ResourceManager.GetString("QRY_AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;CardCode&quot;, T0.&quot;CardName&quot; FROM OCRD T0 INNER JOIN &quot;@UBP1&quot; T1 ON T1.&quot;U_GroupCode&quot; = T0.&quot;GroupCode&quot; INNER JOIN &quot;@OUBP&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T0.&quot;CardType&quot; = &apos;C&apos; AND T2.&quot;U_User&quot; = (SELECT &quot;USER_CODE&quot; FROM OUSR WHERE &quot;INTERNAL_K&quot; = $[USER]).
        /// </summary>
        internal static string QRY_BPByUser {
            get {
                return ResourceManager.GetString("QRY_BPByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;CardCode&quot;, T0.&quot;CardName&quot; FROM OCRD T0 INNER JOIN &quot;@UBP1&quot; T1 ON T1.&quot;U_GroupCode&quot; = T0.&quot;GroupCode&quot; INNER JOIN &quot;@OUBP&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_User&quot; = (SELECT &quot;USER_CODE&quot; FROM OUSR WHERE &quot;INTERNAL_K&quot; = $[USER]).
        /// </summary>
        internal static string QRY_BPByUserForInventory {
            get {
                return ResourceManager.GetString("QRY_BPByUserForInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;CardName&quot;, T0.&quot;CardCode&quot; FROM OCRD T0 INNER JOIN &quot;@UBP1&quot; T1 ON T1.&quot;U_GroupCode&quot; = T0.&quot;GroupCode&quot; INNER JOIN &quot;@OUBP&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T0.&quot;CardType&quot; = &apos;C&apos; AND T2.&quot;U_User&quot; = (SELECT &quot;USER_CODE&quot; FROM OUSR WHERE &quot;INTERNAL_K&quot; = $[USER]).
        /// </summary>
        internal static string QRY_BPNameByUser {
            get {
                return ResourceManager.GetString("QRY_BPNameByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;CardName&quot;, T0.&quot;CardCode&quot; FROM OCRD T0 INNER JOIN &quot;@UBP1&quot; T1 ON T1.&quot;U_GroupCode&quot; = T0.&quot;GroupCode&quot; INNER JOIN &quot;@OUBP&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_User&quot; = (SELECT &quot;USER_CODE&quot; FROM OUSR WHERE &quot;INTERNAL_K&quot; = $[USER]).
        /// </summary>
        internal static string QRY_BPNameByUserForInventory {
            get {
                return ResourceManager.GetString("QRY_BPNameByUserForInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;CardName&quot;, T0.&quot;CardCode&quot; FROM OCRD T0 INNER JOIN &quot;@UBP1&quot; T1 ON T1.&quot;U_GroupCode&quot; = T0.&quot;GroupCode&quot; INNER JOIN &quot;@OUBP&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T0.&quot;CardType&quot; = &apos;S&apos; AND T2.&quot;U_User&quot; = (SELECT &quot;USER_CODE&quot; FROM OUSR WHERE &quot;INTERNAL_K&quot; = $[USER]).
        /// </summary>
        internal static string QRY_BPNameVendorByUser {
            get {
                return ResourceManager.GetString("QRY_BPNameVendorByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;CardCode&quot;, T0.&quot;CardName&quot; FROM OCRD T0 INNER JOIN &quot;@UBP1&quot; T1 ON T1.&quot;U_GroupCode&quot; = T0.&quot;GroupCode&quot; INNER JOIN &quot;@OUBP&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T0.&quot;CardType&quot; = &apos;S&apos; AND T2.&quot;U_User&quot; = (SELECT &quot;USER_CODE&quot; FROM OUSR WHERE &quot;INTERNAL_K&quot; = $[USER]).
        /// </summary>
        internal static string QRY_BPVendorByUser {
            get {
                return ResourceManager.GetString("QRY_BPVendorByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T1.&quot;U_AccountCode&quot;, T2.&quot;AcctName&quot; FROM &quot;@OUAC&quot; T0 JOIN &quot;@UAC1&quot; T1 ON T0.&quot;Code&quot; = T1.&quot;Code&quot; JOIN &quot;OACT&quot; T2 ON T1.&quot;U_AccountCode&quot; = T2.&quot;AcctCode&quot; WHERE T0.&quot;U_User&quot; = (SELECT &quot;USER_CODE&quot; FROM OUSR WHERE &quot;INTERNAL_K&quot; = $[USER]).
        /// </summary>
        internal static string QRY_COAByUser {
            get {
                return ResourceManager.GetString("QRY_COAByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM1&quot; T1 ON T1.&quot;U_Dimension1&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$2001.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension1ByBranch {
            get {
                return ResourceManager.GetString("QRY_Dimension1ByBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM1&quot; T1 ON T1.&quot;U_Dimension1&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1470000032.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension1ByBranchInvCounting {
            get {
                return ResourceManager.GetString("QRY_Dimension1ByBranchInvCounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM1&quot; T1 ON T1.&quot;U_Dimension1&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1470000026.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension1ByBranchInvOpenBal {
            get {
                return ResourceManager.GetString("QRY_Dimension1ByBranchInvOpenBal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM1&quot; T1 ON T1.&quot;U_Dimension1&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1470000029.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension1ByBranchInvPosting {
            get {
                return ResourceManager.GetString("QRY_Dimension1ByBranchInvPosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM1&quot; T1 ON T1.&quot;U_Dimension1&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320002034.0.0]).
        /// </summary>
        internal static string QRY_Dimension1ByBranchJournalEntry {
            get {
                return ResourceManager.GetString("QRY_Dimension1ByBranchJournalEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM1&quot; T1 ON T1.&quot;U_Dimension1&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320002034.0.0]).
        /// </summary>
        internal static string QRY_Dimension1ByBranchJournalVoucher {
            get {
                return ResourceManager.GetString("QRY_Dimension1ByBranchJournalVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM1&quot; T1 ON T1.&quot;U_Dimension1&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = $[$1320000092.0.0].
        /// </summary>
        internal static string QRY_Dimension1ByBranchName {
            get {
                return ResourceManager.GetString("QRY_Dimension1ByBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM1&quot; T1 ON T1.&quot;U_Dimension1&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320000098.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension1ByBranchTransfer {
            get {
                return ResourceManager.GetString("QRY_Dimension1ByBranchTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM1&quot; T1 ON T1.&quot;U_Dimension1&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320000098.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension1ByBranchTransferReq {
            get {
                return ResourceManager.GetString("QRY_Dimension1ByBranchTransferReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM2&quot; T1 ON T1.&quot;U_Dimension2&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$2001.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension2ByBranch {
            get {
                return ResourceManager.GetString("QRY_Dimension2ByBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM2&quot; T1 ON T1.&quot;U_Dimension2&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1470000032.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension2ByBranchInvCounting {
            get {
                return ResourceManager.GetString("QRY_Dimension2ByBranchInvCounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM2&quot; T1 ON T1.&quot;U_Dimension2&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1470000026.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension2ByBranchInvOpenBal {
            get {
                return ResourceManager.GetString("QRY_Dimension2ByBranchInvOpenBal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM2&quot; T1 ON T1.&quot;U_Dimension2&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1470000029.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension2ByBranchInvPosting {
            get {
                return ResourceManager.GetString("QRY_Dimension2ByBranchInvPosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM2&quot; T1 ON T1.&quot;U_Dimension2&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320002034.0.0]).
        /// </summary>
        internal static string QRY_Dimension2ByBranchJournalEntry {
            get {
                return ResourceManager.GetString("QRY_Dimension2ByBranchJournalEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM2&quot; T1 ON T1.&quot;U_Dimension2&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320002034.0.0]).
        /// </summary>
        internal static string QRY_Dimension2ByBranchJournalVoucher {
            get {
                return ResourceManager.GetString("QRY_Dimension2ByBranchJournalVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM2&quot; T1 ON T1.&quot;U_Dimension2&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = $[$1320000092.0.0].
        /// </summary>
        internal static string QRY_Dimension2ByBranchName {
            get {
                return ResourceManager.GetString("QRY_Dimension2ByBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM2&quot; T1 ON T1.&quot;U_Dimension2&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320000098.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension2ByBranchTransfer {
            get {
                return ResourceManager.GetString("QRY_Dimension2ByBranchTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM2&quot; T1 ON T1.&quot;U_Dimension2&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320000098.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension2ByBranchTransferReq {
            get {
                return ResourceManager.GetString("QRY_Dimension2ByBranchTransferReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM3&quot; T1 ON T1.&quot;U_Dimension3&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$2001.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension3ByBranch {
            get {
                return ResourceManager.GetString("QRY_Dimension3ByBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM3&quot; T1 ON T1.&quot;U_Dimension3&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1470000032.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension3ByBranchInvCounting {
            get {
                return ResourceManager.GetString("QRY_Dimension3ByBranchInvCounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM3&quot; T1 ON T1.&quot;U_Dimension3&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1470000026.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension3ByBranchInvOpenBal {
            get {
                return ResourceManager.GetString("QRY_Dimension3ByBranchInvOpenBal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM3&quot; T1 ON T1.&quot;U_Dimension3&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1470000029.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension3ByBranchInvPosting {
            get {
                return ResourceManager.GetString("QRY_Dimension3ByBranchInvPosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM3&quot; T1 ON T1.&quot;U_Dimension3&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320002034.0.0]).
        /// </summary>
        internal static string QRY_Dimension3ByBranchJournalEntry {
            get {
                return ResourceManager.GetString("QRY_Dimension3ByBranchJournalEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM3&quot; T1 ON T1.&quot;U_Dimension3&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320002034.0.0]).
        /// </summary>
        internal static string QRY_Dimension3ByBranchJournalVoucher {
            get {
                return ResourceManager.GetString("QRY_Dimension3ByBranchJournalVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM3&quot; T1 ON T1.&quot;U_Dimension3&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = $[$1320000092.0.0].
        /// </summary>
        internal static string QRY_Dimension3ByBranchName {
            get {
                return ResourceManager.GetString("QRY_Dimension3ByBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM3&quot; T1 ON T1.&quot;U_Dimension3&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320000098.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension3ByBranchTransfer {
            get {
                return ResourceManager.GetString("QRY_Dimension3ByBranchTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM3&quot; T1 ON T1.&quot;U_Dimension3&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320000098.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension3ByBranchTransferReq {
            get {
                return ResourceManager.GetString("QRY_Dimension3ByBranchTransferReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM4&quot; T1 ON T1.&quot;U_Dimension4&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$2001.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension4ByBranch {
            get {
                return ResourceManager.GetString("QRY_Dimension4ByBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM4&quot; T1 ON T1.&quot;U_Dimension4&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1470000032.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension4ByBranchInvCounting {
            get {
                return ResourceManager.GetString("QRY_Dimension4ByBranchInvCounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM4&quot; T1 ON T1.&quot;U_Dimension4&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1470000026.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension4ByBranchInvOpenBal {
            get {
                return ResourceManager.GetString("QRY_Dimension4ByBranchInvOpenBal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM4&quot; T1 ON T1.&quot;U_Dimension4&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1470000029.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension4ByBranchInvPosting {
            get {
                return ResourceManager.GetString("QRY_Dimension4ByBranchInvPosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM4&quot; T1 ON T1.&quot;U_Dimension4&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320002034.0.0]).
        /// </summary>
        internal static string QRY_Dimension4ByBranchJournalEntry {
            get {
                return ResourceManager.GetString("QRY_Dimension4ByBranchJournalEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM4&quot; T1 ON T1.&quot;U_Dimension4&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320002034.0.0]).
        /// </summary>
        internal static string QRY_Dimension4ByBranchJournalVoucher {
            get {
                return ResourceManager.GetString("QRY_Dimension4ByBranchJournalVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM4&quot; T1 ON T1.&quot;U_Dimension4&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = $[$1320000092.0.0].
        /// </summary>
        internal static string QRY_Dimension4ByBranchName {
            get {
                return ResourceManager.GetString("QRY_Dimension4ByBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM4&quot; T1 ON T1.&quot;U_Dimension4&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320000098.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension4ByBranchTransfer {
            get {
                return ResourceManager.GetString("QRY_Dimension4ByBranchTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM4&quot; T1 ON T1.&quot;U_Dimension4&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320000098.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension4ByBranchTransferReq {
            get {
                return ResourceManager.GetString("QRY_Dimension4ByBranchTransferReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM5&quot; T1 ON T1.&quot;U_Dimension5&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$2001.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension5ByBranch {
            get {
                return ResourceManager.GetString("QRY_Dimension5ByBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM5&quot; T1 ON T1.&quot;U_Dimension5&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1470000032.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension5ByBranchInvCounting {
            get {
                return ResourceManager.GetString("QRY_Dimension5ByBranchInvCounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM5&quot; T1 ON T1.&quot;U_Dimension5&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1470000026.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension5ByBranchInvOpenBal {
            get {
                return ResourceManager.GetString("QRY_Dimension5ByBranchInvOpenBal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM5&quot; T1 ON T1.&quot;U_Dimension5&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1470000029.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension5ByBranchInvPosting {
            get {
                return ResourceManager.GetString("QRY_Dimension5ByBranchInvPosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM5&quot; T1 ON T1.&quot;U_Dimension5&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320002034.0.0]).
        /// </summary>
        internal static string QRY_Dimension5ByBranchJournalEntry {
            get {
                return ResourceManager.GetString("QRY_Dimension5ByBranchJournalEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM5&quot; T1 ON T1.&quot;U_Dimension5&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320002034.0.0]).
        /// </summary>
        internal static string QRY_Dimension5ByBranchJournalVoucher {
            get {
                return ResourceManager.GetString("QRY_Dimension5ByBranchJournalVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM5&quot; T1 ON T1.&quot;U_Dimension5&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = $[$1320000092.0.0].
        /// </summary>
        internal static string QRY_Dimension5ByBranchName {
            get {
                return ResourceManager.GetString("QRY_Dimension5ByBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM5&quot; T1 ON T1.&quot;U_Dimension5&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320000098.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension5ByBranchTransfer {
            get {
                return ResourceManager.GetString("QRY_Dimension5ByBranchTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.&quot;OcrCode&quot;, T0.&quot;OcrName&quot; FROM OOCR T0 INNER JOIN &quot;@BDM5&quot; T1 ON T1.&quot;U_Dimension5&quot; = T0.&quot;OcrCode&quot; INNER JOIN &quot;@OBDM&quot; T2 ON T2.&quot;Code&quot; = T1.&quot;Code&quot; WHERE T2.&quot;U_Branch&quot; = (SELECT &quot;BPLName&quot; FROM OBPL WHERE &quot;BPLId&quot; = $[$1320000098.0.NUMBER]).
        /// </summary>
        internal static string QRY_Dimension5ByBranchTransferReq {
            get {
                return ResourceManager.GetString("QRY_Dimension5ByBranchTransferReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T1.&quot;U_Project&quot;, T2.&quot;PrjName&quot; FROM &quot;@OUPR&quot; T0 INNER JOIN &quot;@UPR1&quot; T1 ON T1.&quot;Code&quot; = T0.&quot;Code&quot; INNER JOIN &quot;OPRJ&quot; T2 ON T2.PrjCode = T1.&quot;U_Project&quot; WHERE T0.&quot;U_User&quot; = (SELECT &quot;USER_CODE&quot; FROM OUSR WHERE &quot;INTERNAL_K&quot; = $[USER]).
        /// </summary>
        internal static string QRY_ProjectsByUser {
            get {
                return ResourceManager.GetString("QRY_ProjectsByUser", resourceCulture);
            }
        }
    }
}
