//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDKUtilities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDKUtilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;env:Envelope xmlns:env=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        /// &lt;env:Header&gt;
        ///  &lt;SessionID&gt;{0}&lt;/SessionID&gt;
        /// &lt;/env:Header&gt;
        /// &lt;env:Body&gt;
        ///   &lt;dis:AddObject xmlns:dis=&quot;http://www.sap.com/SBO/DIS&quot; CommandID=&quot;{1}&quot;&gt;
        ///   {2}
        ///   &lt;/dis:AddObject&gt;
        /// &lt;/env:Body&gt;
        ///&lt;/env:Envelope&gt;.
        /// </summary>
        internal static string AddObjectSoapRequest {
            get {
                return ResourceManager.GetString("AddObjectSoapRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;BOM&gt;
        ///&lt;BO&gt;
        ///	&lt;AdmInfo&gt;
        ///	&lt;Object&gt;oBusinessPartners&lt;/Object&gt;
        ///	&lt;Version&gt;2&lt;/Version&gt;
        ///	&lt;/AdmInfo&gt;
        ///	&lt;BusinessPartners&gt;
        ///	&lt;row&gt;
        ///	&lt;CardCode&gt;{0}&lt;/CardCode&gt;
        ///	&lt;CardName&gt;{1}&lt;/CardName&gt;
        ///	&lt;/row&gt;
        ///	&lt;/BusinessPartners&gt;
        ///&lt;/BO&gt;
        ///&lt;/BOM&gt;.
        /// </summary>
        internal static string BPSoapRequest {
            get {
                return ResourceManager.GetString("BPSoapRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;env:Envelope xmlns:env=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///  &lt;env:Body&gt;
        ///    &lt;dis:Login xmlns:dis=&quot;http://www.sap.com/SBO/DIS&quot;&gt;
        ///      &lt;DatabaseServer&gt;{0}&lt;/DatabaseServer&gt;
        ///      &lt;DatabaseName&gt;{1}&lt;/DatabaseName&gt;
        ///      &lt;DatabaseType&gt;{2}&lt;/DatabaseType&gt;
        ///      &lt;CompanyUsername&gt;{3}&lt;/CompanyUsername&gt;
        ///	  &lt;CompanyPassword&gt;{4}&lt;/CompanyPassword&gt;
        ///	  &lt;Language&gt;{5}&lt;/Language&gt;
        ///      &lt;LicenseServer&gt;{6}&lt;/LicenseServer&gt;
        ///    &lt;/dis:Login&gt;
        ///  &lt;/env:Body&gt;
        ///&lt;/env:Envelope&gt;.
        /// </summary>
        internal static string DIServerLoginSOAP {
            get {
                return ResourceManager.GetString("DIServerLoginSOAP", resourceCulture);
            }
        }
    }
}
